### ISSUE TITLE
Not responding after entering play mode

### ISSUE THREAD

**Issue by laicasaane** [Antoshidza/Age-of-Sprites#5]
I'm at the latest commit with NSprites 2.0.0.
The editor will be not responding whenever entering play mode.

**Comment by Antoshidza** [comment]
I can't reproduce such behaviour. Also before release 2.0.0 I've ensured that build works. So I want to firstly ask a common question, I'm sorry if it is too dumb. Can it be that you hit play with `Entities Hierarchy` window opened? Asking because I and some forum member we was facing this problem. This window makes very hard calculations when you create tones of entities, which happens in this project right on start, and it seems like editor doesn't respond.

**Comment by laicasaane** [comment]
> Can it be that you hit play with Entities Hierarchy window opened?

That's right. This is the case!

**Comment by Antoshidza** [comment]
I was thinking about solving this by spawning environment only on demand, but also I think that game architecture shouldn't depend on editor UI problems, if I need to spawn 100k entities in 1st frame then opened window shouldn't stop me from that.
